AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Inky-Backend

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Resources:
  InkyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Inky-Api-Main
      StageName: Prod
      Auth:
        ApiKeyRequired: true 

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref InkyApi
            Path: /hello
            Method: get
            Auth:
              ApiKeyRequired: true  

  GoodbyeWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: goodbye_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Timeout: 10
      Layers:
        - arn:aws:lambda:us-east-1:831926586049:layer:requests:1
      Events:
        GoodbyeWorld:
          Type: Api
          Properties:
            RestApiId: !Ref InkyApi
            Path: /goodbye
            Method: get
            Auth:
              ApiKeyRequired: false

  UserCredReceivePrivateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Functions/UserCred-Receive-Private/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole

  UserCredSendPublicFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Functions/UserCred-Send-Public/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "lambda:InvokeFunction"
              Resource: !GetAtt UserCredReceivePrivateFunction.Arn
      Environment:
        Variables:
          PRIVATE_FUNCTION_ARN: !GetAtt UserCredReceivePrivateFunction.Arn
      Events:
        UserCredSendPublicEvent:
          Type: Api
          Properties:
            RestApiId: !Ref InkyApi
            Path: /usercredsendpublic
            Method: post
            Auth:
              ApiKeyRequired: false

  MyUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: MyApiUsagePlan
      Description: "Usage plan for the Inky API"
      ApiStages:
        - ApiId: !Ref InkyApi
          Stage: !Ref InkyApiProdStage  # Reference the correct stage

  MyApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Enabled: true
      Name: MyApiKey

  MyUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref MyApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref MyUsagePlan

Outputs:
  InkyApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${InkyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  GoodbyeWorldFunction:
    Description: Goodbye World Lambda Function ARN
    Value: !GetAtt GoodbyeWorldFunction.Arn
  UserCredReceivePrivateFunctionArn:
    Description: UserCred Receive Private Function ARN
    Value: !GetAtt UserCredReceivePrivateFunction.Arn
  UserCredSendPublicFunctionArn:
    Description: UserCred Send Public Function ARN
    Value: !GetAtt UserCredSendPublicFunction.Arn

  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
